### PR TITLE
Lux Dock Menu Implementation Draft

### PR DESCRIPTION
**Pull request by theetherGit**
Implemented - https://luxe.guhrodrigues.com/ui/dock
Still have some issues related to animation.

https://github.com/SikandarJODD/svelte-animations/assets/71087863/0902c550-fd1b-4942-a4f3-65cabe98cf73

### CODE REVIEW

**Comment by SikandarJODD** [comment]
Thanks a lot...i really learn 2 things..here i was literally coping the content of files and pasting it...

**Review by SikandarJODD — APPROVED** [review]

**Comment by SikandarJODD** [comment]
About Dock Components.. i would learn from your code...step by step

**Comment by theetherGit** [comment]
@SikandarJODD It's not completed yet.

**Comment by theetherGit** [comment]
@SikandarJODD Thanks for the patch.

**Comment by SikandarJODD** [comment]
As it gave me error while publishing the code : 
Error : Top level await is not allowed was show by vercel so i just commented it out...and added the code

**Pull request merged**
